version: "3"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:1337
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    env_file:
      - .env
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:1337
    restart: always
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    ports:
       - "9000:9000"
    env_file:
      - .env
    networks:
      - inception

  
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:1337
    restart: always
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception

networks:
    inception:
      name: inception
      driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device:  /home/mmounaji/data/wordpress/
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/mmounaji/data/mariadb/
      o: bind
