version: "3"

services:
  mariadb:
    build: /Users/mmounaji/safi_baraka/srcs/requirements/mariadb
    container_name: mariadb
    image: mariadb:1337
    restart: always
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception
    expose:
      - "3306"
    env_file:
      - .env
  
  wordpress:
    build: /Users/mmounaji/safi_baraka/srcs/requirements/wordpress
    container_name: wordpress
    image: wordpress:1337
    restart: always
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception

  
  nginx:
    build: /Users/mmounaji/safi_baraka/srcs/requirements/nginx
    container_name: nginx
    image: nginx:1337
    restart: always
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception

networks:
    inception:
      driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device:  /Users/mmounaji/safi_baraka/wordpress
      o: bind
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/mmounaji/safi_baraka/mariadb
      o: bind