version: '3'

services:
  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
    restart: always
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    networks:
      - inception
    restart : always

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mariadb
    
networks:
  inception:
    driver: bridge
