version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception

  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - /Users/mmounaji/Desktop/inception/mariadb:/var/lib/mysql  # Corrected volume mapping

networks:
  inception:
